# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - run: docker kill itsallfoodthings_psql_db
    - run: docker kill itsallfoodthings_node_express
    - run: mv /var/www/itsallfoodthings-api /var/www/itsallfoodthings-api/old
    - run: mkdir /var/www/itsallfoodthings-api
    - run: cp -r /var/www/actions-runner/_work/itsallfoodthings-api/itsallfoodthings-api/. itsallfoodthings-api
    - run: cp /var/www/itsallfoodthings-api-old/.env /var/www/itsallfoodthings-api
    - run: rm -rf /var/www/itsallfoodthings-api/old
    - run: cd /var/www/itsallfoodthings-api
    - run: cd docker-compose up
